### ISSUE TITLE
Verifying AdvantageKit in Sim

### ISSUE THREAD

**Issue by minhnguyenbhs** [team401/high-key-2024#85] opened 2024-12-11 23:36 UTC

**Comment by Sojo123456** [comment] 2024-12-12 00:27
@jkleiber I think that everything auto is already working in sim?
![{9C8F7468-7A26-4852-9513-1C68E2B8215C}](https://github.com/user-attachments/assets/4c4011ff-82fe-4d77-889d-4d2f75ae377a)

**Comment by Sojo123456** [comment] 2024-12-12 00:27
There's a weird issue that shows up a bit concerningly often where the odometry stops working in both teleop and auto but i don't think that's a code issue

**Comment by Sojo123456** [comment] 2024-12-12 00:28
the problem is resolved by closing either glass or advantagekit and reopening it, not changes in code

**Comment by Sojo123456** [comment] 2024-12-12 00:30
sorry, this is Minh! I didn't realize that someone else was signed in (sorry Henry!!)

**Comment by minhnguyenbhs** [comment] 2024-12-14 16:47
hello! I'm not sure how to record a video of Advantagekit on my desktop, what should I show as evidence that this may already be working?

**Comment by jkleiber** [comment] 2024-12-14 20:38
You could post screenshots of advantage scope potentially

**Comment by minhnguyenbhs** [comment] 2024-12-14 21:55
got it! Which screenshots other than the one i posted at shop at the top of the page should I include?

**Comment by jkleiber** [comment] 2024-12-15 01:09
@minhnguyenbhs it would be helpful to post the path the robot took. But I don't think this is a very high priority issue right now so maybe your time would be better spent on this: https://github.com/team401/coppercore/issues/73

**Comment by jkleiber** [comment] 2024-12-15 01:09
(I think I'm going to close this ticket for now and try to make a more clear plan for how we should do this in 2025)
Thanks for looking into it @minhnguyenbhs !

**Closed by jkleiber** 2024-12-15 01:09 UTC
